<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Commande <?= $_GET['commande'] ;?></title>
</head>
<body>
	<h1>Commande <?= $_GET['commande'] ;?></h1>
	<form action="admin.php?page=deconnexion" method="post">
		<input type="submit" name="deconnexion" value="deconnexion">
	</form>
	<a href="admin.php">Retour</a>
	<section>
	<?php foreach($commande as $unProduit): ?>
		<table>
			<figure>
				<img src="<?= $unProduit['image'] ;?>">
			</figure>
			<div>
				<h2><?= $unProduit['nom'] ;?></h2>
				<p>Description produit : <?= $unProduit['description'] ;?></p>
				<p>Pays : <?= $unProduit['pays'] ;?></p>
				<p>Quantitée : <?= $unProduit['quantitee'] ;?>kg</p>
				<p>Prix commande : <?= intval($unProduit['prix_commande'])/100 ;?> euros</p>
				<p>Status commande : 
							<?php if($unProduit['status'] === '0'):
								echo 'Payement non effectué';
							elseif($unProduit['status'] === '2'):
								echo 	'probleme dans le payment';
							elseif($unProduit['status'] === '4'):
								echo 'Payement effectuer, preparationd e la commande';
							endif; ?></p>
			</div>
		</table>
	<?php endforeach; ?>
	</section>
</body>
</html>